# Generated by Django 4.1.5 on 2023-01-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_alter_trip_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='DayIncome',
        ),
    ]
