# Generated by Django 4.1.5 on 2023-01-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_rename_trip_dayincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayincome',
            name='type',
            field=models.CharField(choices=[('In', 'Income'), ('D', 'Decrease'), ('I', 'Increase')], default='In', max_length=2),
        ),
    ]
