# Generated by Django 4.1.5 on 2023-01-11 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_dayincome_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('type', models.CharField(choices=[('In', 'Income'), ('D', 'Decrease'), ('I', 'Increase')], default='In', max_length=2)),
                ('value', models.BigIntegerField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.courier')),
            ],
            options={
                'ordering': ['Date', 'courier'],
            },
        ),
        migrations.DeleteModel(
            name='DayIncome',
        ),
    ]
