# Generated by Django 4.1.5 on 2023-01-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0006_incomeperday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncomePerDay',
        ),
    ]
